# Site settings
title: AssoB.it
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Sito dell'Associazione AssoB.it.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://assobit.github.io/" # the base hostname & protocol for your site
author: "AssoB.it"
excerpt_separator: ""
twitter_username: jekyllrb
github_username:  jekyll
github: "http://github.com/giacomozucco/assobit.github.io"
gems: [jekyll-paginate]
paginate: 3
paginate_path: "/news/page:num/"

# Build settings
markdown: kramdown
